### ISSUE TITLE
Expressions with comments in .vimrc are silently ignored

### ISSUE THREAD

**Issue by nadya-p** [hluk/FakeVim#60]
I'm using FakeVim in QtCreator. I've noticed that 
`set clipboard=unnamed`
gives the expected effect (can copy to the system clipboard), while
`set clipboard=unnamed " test comment`
does not.

**Comment by hluk** [comment]
This should be fixed by updating code here from latest QtCreator: https://github.com/hluk/FakeVim/pull/61

If you only use QtCreator (and not standalone FakeVim library) please update the app to the latest version - it has been fixed some time ago. See: https://bugreports.qt.io/browse/QTCREATORBUG-26254
